/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Snowball
 #	author : miyako
 #	2016/01/15
 #
 # --------------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h> /* for malloc, free */
#include <string.h> /* for memmove */
#include <ctype.h>  /* for isupper, tolower */

#include <iostream>
#include <sstream>
#include <iterator>

#include "libstemmer.h"

// --- Snowball
void Snowball(sLONG_PTR *pResult, PackagePtr pParams);

typedef enum
{
				Snowball_Danish = 0,
				Snowball_Dutch,
				Snowball_English,
				Snowball_Finnish,
				Snowball_French,
				Snowball_German,
				Snowball_Hungarian,
				Snowball_Italian,
				Snowball_Norwegian,
				Snowball_Portuguese,
				Snowball_Romanian,
				Snowball_Russian,
				Snowball_Spanish,
				Snowball_Swedish,
				Snowball_Turkish
} Snowball_Language;